version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db/myapp_development
      RAILS_ENV: test
      CAPYBARA_SERVER_HOST: '0.0.0.0'
      CAPYBARA_APP_HOST: 'http://web:3000'
    tty: true
    stdin_open: true

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - "5433:5432"

volumes:
  postgres_data: