default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: your_mysql_username
  password: your_mysql_password
  host: localhost
  database: your_development_database_name

test:
  <<: *default
  adapter: mysql2
  username: your_mysql_username
  password: your_mysql_password
  host: localhost
  database: your_test_database_name

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>